@startuml MDD Ubik
skinparam style strictuml
skinparam defaultfontname Verdana
left to right direction
hide empty members
'skinparam linetype ortho
title MDD Ubik

class Usager <<role>> {
    id: String
    firstName: String
    lastName: String
    email: email
    phoneNum: String
    brands: Brands
    socialMediaAccounts: SocialMedia[]
    subcription: Membership
    timezone: TZ
    savedAds: ad[]
    savedSolgans: slogan[]

}
class socialMediaAccounts{
    SocialMedia[]
}

class Ad{
    text: String
    dateOfGeneration:Date 
}

class Slogan{
    text: String
    dateOfGeneration:Date 
}

class Brand{

}


class SocialMedia{
    platform
    Userid
    APIToken
}

class Membership{

}

class DateRange{

}



class Post <<Conteneurs>> {
  
  ad: Ad.Text
  slogan: Slogan.text 
  image : URL
}




@enduml 

